require('aden.plugins')
require('aden.keybindings')
require("aden.options")
require("aden.nvim-tree")
require("aden.ts")
require("aden.line-config")
require('aden.buffer-config')
require('aden.autopairs-config')
require('aden.dashboard-config')
require('aden.which-key')
require('aden.telescope')
require('aden.lsp')
require('aden.colorizer')
require('aden.blankline-config')
vim.cmd('colorscheme nord')

