require('andre.plugins')
require('andre.keybindings')
require("andre.options")
require("andre.nvim-tree")
require("andre.ts")
require("andre.line-config")
require('andre.buffer-config')
require('andre.autopairs-config')
require('andre.dashboard-config')
require('andre.which-key')
require('andre.telescope')
require('andre.lsp')
require('andre.colorizer')
require('andre.blankline-config')
vim.cmd('colorscheme nord')

